name: Data Preprocessing

on:
  push:
    paths:
      - preprocessing/automate_Muchlish.py
      - namadataset_raw/**
  workflow_dispatch:  # memungkinkan manual run

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Muchlish.py

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: updated_preprocessed_data
          path: namadataset_preprocessing/updated_pollution_dataset_preprocessing.csv
          