name: Data Preprocessing

on:
  push:
    paths:
      - preprocessing/automate_Muchlish.py
      - dataset_raw/**
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Muchlish.py

      - name: Upload preprocessed datasets
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed_csv_files
          path: |
            train_data_scaled.csv
            test_data_scaled.csv

      - name: Commit hasil preprocessing ke repo
        run: |
          mkdir -p dataset_preprocessing
          mv train_data_scaled.csv dataset_preprocessing/
          mv test_data_scaled.csv dataset_preprocessing/
    
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dataset_preprocessing/train_data_scaled.csv dataset_preprocessing/test_data_scaled.csv

          if git diff --cached --quiet; then
            echo "Tidak ada perubahan yang perlu dikomit."
          else
            git commit -m "Update hasil preprocessing"
            git push origin main
          fi
